FROM python:3.8.9-slim

ENV PIPENV_VENV_IN_PROJECT=true
ENV PATH=$PATH:/opt/.venv/bin
ENV PYTHONPATH=/opt/src

COPY mypy.ini /opt/mypy.ini
COPY Pipfile.lock /opt/Pipfile.lock
COPY pylintrc /opt/pylintrc
COPY pyproject.toml /opt/pyproject.toml
COPY README.md /opt/README.md
COPY ./src /opt/src
COPY ./test /opt/test

WORKDIR opt

RUN pip install --upgrade pip
RUN pip install pipenv
RUN pipenv sync --dev

# Format
RUN echo 'Format Check'
RUN black ./src --config=pyproject.toml --check
# Lint
RUN echo 'Lint Check'
RUN pylint ./src --rcfile=pylintrc
# Type Check
RUN echo 'Type Check'
RUN mypy ./src --config-file=mypy.ini
# Unittest
RUN echo 'Unittest Check'
RUN pytest ./test
